
#include "count.h" 

int main( int argc , char **argv ) 
{
	int cut = 0 ; 
	if( argc > 1 ) 
		cut = atoi( argv[1] ) ; 
	
	char fasta[] = ">NODE_9080_length_266_cov_4.109_ID_18159\nGCCGAAGCCTGCTCGATGAAATCGGCAGGCGACTGGGCGAAAGCACTGCTGGCGCCGAGGCCCAGCAGCATCGCGAAACTGGCGGTGCGTAACCGGATAGCCATGCGGCTCATGATGGGTTCCTCCAGGTAATAAACAGGTGCAGGGAAACGAGCCCCGCTCTGAATCTGAATTTTCAGGGCGGTAAAGGTTTAGAAAAAACTTGCCAGTGCGACGAACGGTCGTCAAATCCTGCTGCCAAACAGGCCCGACAATACTCCCTGCAC\n>NODE_9081_length_266_cov_11.5024_ID_18161\nGTGCTGAGATGTGTCACAATGCCACTGTAGGCAGAGCCTAAACAAGAGTTACATGAACCAGGTGATCAGTGCAGAGATACATCGCAATGTACCTGTAGGCAGAGCCTTGACAAGTGGTACATCACCTGGGTGATCATTGTAGGGATATGTCACAAAGCACCCTGTAGGCAGATCCTAGAGAAGAGTTATATCACCTGGGTGATCAGTGCAGAGGTAGGTCACAATCCCCCTTTAGCAGAGCCTATACAAGAGTTATATCACCTGGT\n>NODE_9082_length_266_cov_3.54976_ID_18163\nCCTAGCGCATAGGGGGCGAGCGCTACCGCCCAAATGCCCAGAAACAGCAGATAGAACAGCGAAATGCCCGCCACATCCAAGCGCCCCAGGGTGATGGCCGAGGTCTTGATGCCGATCTTGAGGTCGTCGTCGCGGTCCACCATGGCGTATTCGGTGTCGTAGGCCAGCACCCAGAACATATTGCCCAGCCACATCCACCACGCCACTGCGGGCACGCTACCCTGCACGGCGGCAAACGCGATGACGATGCCGAAGTTGAACGCCTG\n>NODE_9083_length_266_cov_3.21327_ID_18165\nGTCTGCCTTGCCAGCCCGCTCAGAGAAGGGTATAAGAGACAGCTATGACGAGGCCTGGCAGCGCCTGAACCCCGGGATGCAGCGGGTGAACCTGCCGGACGACAAGCCGGTCGCCGGGGCCACGCGCGGCTCCGGCCGCACGGCAGTGTTCGTGAAAGATAACTGCGTGGCCTGCGGCCAGCTCGTGCAGCGCCTGCAATCCTCGGGCGCCGAATTCGACCTGTACATGGTCGGCAGCCGCCAGGACGACGCGCGCATCCGCGATT" ; 
	
	char seq1[] = "GCCGAAGCCTGCTCGATGAAATCGGCAGGCGACTGGGCGAAAGCACTGCTGGCGCCGAGGCCCAGCAGCATCGCGAAACTGGCGGTGCGTAACCGGATAGCCATGCGGCTCATGATGGGTTCCTCCAGGTAATAAACAGGTGCAGGGAAACGAGCCCCGCTCTGAATCTGAATTTTCAGGGCGGTAAAGGTTTAGAAAAAACTTGCCAGTGCGACGAACGGTCGTCAAATCCTGCTGCCAAACAGGCCCGACAATACTCCCTGCAC" ; 
	char seq2[] = "GTGCTGAGATGTGTCACAATGCCACTGTAGGCAGAGCCTAAACAAGAGTTACATGAACCAGGTGATCAGTGCAGAGATACATCGCAATGTACCTGTAGGCAGAGCCTTGACAAGTGGTACATCACCTGGGTGATCATTGTAGGGATATGTCACAAAGCACCCTGTAGGCAGATCCTAGAGAAGAGTTATATCACCTGGGTGATCAGTGCAGAGGTAGGTCACAATCCCCCTTTAGCAGAGCCTATACAAGAGTTATATCACCTGGT" ; 
	char seq3[] = "CCTAGCGCATAGGGGGCGAGCGCTACCGCCCAAATGCCCAGAAACAGCAGATAGAACAGCGAAATGCCCGCCACATCCAAGCGCCCCAGGGTGATGGCCGAGGTCTTGATGCCGATCTTGAGGTCGTCGTCGCGGTCCACCATGGCGTATTCGGTGTCGTAGGCCAGCACCCAGAACATATTGCCCAGCCACATCCACCACGCCACTGCGGGCACGCTACCCTGCACGGCGGCAAACGCGATGACGATGCCGAAGTTGAACGCCTG" ; 
	char seq4[] = "GTCTGCCTTGCCAGCCCGCTCAGAGAAGGGTATAAGAGACAGCTATGACGAGGCCTGGCAGCGCCTGAACCCCGGGATGCAGCGGGTGAACCTGCCGGACGACAAGCCGGTCGCCGGGGCCACGCGCGGCTCCGGCCGCACGGCAGTGTTCGTGAAAGATAACTGCGTGGCCTGCGGCCAGCTCGTGCAGCGCCTGCAATCCTCGGGCGCCGAATTCGACCTGTACATGGTCGGCAGCCGCCAGGACGACGCGCGCATCCGCGATT" ; 
	
	int tet[4][256] ; 
	
	kmerCounter ( seq1 , cut , tet[0] ) ; 
	kmerCounter ( seq2 , cut , tet[1] ) ; 
	kmerCounter ( seq3 , cut , tet[2] ) ; 
	kmerCounter ( seq4 , cut , tet[3] ) ; 
	
	int i , j ; 
	for( i = 0 ; i < 4 ; i++ ) 
	{
		for( j = 0 ; j < 256 ; j++ ) 
			fprintf( stderr , "%i " , tet[i][j] ) ; 
		fprintf( stderr , "\n" ) ; 
	}
	
	return 0 ; 
}

